package emp.data.service.mysql.controller;

import emp.data.service.mysql.dao.Employee;
import emp.data.service.mysql.repository.EmployeeRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

@RestController // This means that this class is a Rest Controller
@RequestMapping(path="/app/v1")
public class EmployeeController {

    @Autowired // This means to get the bean called empRepository, Which is auto-generated by Spring, we will use it to handle the data
    private EmployeeRepository empRepository;

    //http://localhost:8080/app/v1/add?name=Rockyy&email=abcd@gmail.com
    @PostMapping(path="/add") // Map ONLY POST Requests
    public String addNewUser (@RequestParam String name, @RequestParam String email) {
        // @RequestParam means it is a parameter from the GET or POST request

        Employee n = new Employee();
        n.setName(name);
        n.setEmail(email);
        empRepository.save(n);
        return "Saved";
    }

    //http://localhost:8080/app/v1/all
    @GetMapping(value = "/all")
    public Iterable<Employee> getAllUsers() {
        // This returns a JSON or XML with the users
        return empRepository.findAll();
    }

}
